// Mermaid version compatibility information
// This file is automatically generated and should not be edited manually
export const MERMAID_VERSION_INFO = {
  validatedAgainst: "11.12.0",
  lastValidated: "2024-10-15",
  cliVersion: "@mermaid-js/mermaid-cli@11.12.0"
};
